server:
  port: 8080
  servlet:
    context-path: /community

spring:
  profiles:
    active: develop
  # DataSourceProperties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?userSSL=false
    username: root
    password: abc123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: test@outlook.com
    password: test
    properties:
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  # RedisProperties
  data:
    redis:
      host: 172.20.68.10
  kafka:
    #    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    scheduling:
      pool:
        size: 5
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# caffeine
caffeine:
  post:
    initial-capacity: 5
    max-size: 10
    expire-second: 180

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: info,caches
